import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";
import Header from "@/components/ui/header";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Felipe Benini - CS Student",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased h-[200dvh] bg-[#18181b]`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
